import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fff8f7",
        "surface-dim": "#e2d8d7",
        "surface-bright": "#fff8f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fcf1f1",
        "surface-container": "#f6ebeb",
        "surface-container-high": "#f0e6e5",
        "surface-container-highest": "#eae0e0",
        "on-surface": "#1f1a1b",
        "on-surface-variant": "#564241",
        "inverse-surface": "#342f2f",
        "inverse-on-surface": "#f9eeee",
        "outline": "#897170",
        "outline-variant": "#dcc0bf",
        "surface-tint": "#a13d3f",
        "on-primary": "#ffffff",
        "primary-container": "#f47c7c",
        "on-primary-container": "#6c151c",
        "inverse-primary": "#ffb3b1",
        "secondary": "#765751",
        "on-secondary": "#ffffff",
        "secondary-container": "#fdd3cb",
        "on-secondary-container": "#795953",
        "tertiary": "#645e4f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a79f8d",
        "on-tertiary-container": "#3b3629",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdad8",
        "primary-fixed-dim": "#ffb3b1",
        "on-primary-fixed": "#410007",
        "on-primary-fixed-variant": "#82252a",
        "secondary-fixed": "#ffdad3",
        "secondary-fixed-dim": "#e6bdb6",
        "on-secondary-fixed": "#2c1611",
        "on-secondary-fixed-variant": "#5c403a",
        "tertiary-fixed": "#f5f0e8",
        "tertiary-fixed-dim": "#e8e0d0",
        "on-tertiary-fixed": "#1f1b0f",
        "on-tertiary-fixed-variant": "#4c4638",
        "background": "#fff8f7",
        "on-background": "#1f1a1b",
        "surface-variant": "#eae0e0",
        primary: {
          DEFAULT: "#a13d3f",
          50:  "#FDF2EF",
          100: "#FAE0D9",
          500: "#a13d3f",
          600: "#82252a",
        },
        warm: {
          50:  "#FFF8F4",
          100: "#FEEEE6",
        },
      },
      fontFamily: {
        sans:  ["var(--font-pretendard)", "system-ui", "sans-serif"],
        serif: ["var(--font-noto-serif)", "serif"],
        display: ["var(--font-be-vietnam-pro)", "var(--font-pretendard)", "system-ui", "sans-serif"],
        body: ["var(--font-plus-jakarta-sans)", "var(--font-pretendard)", "system-ui", "sans-serif"],
        "display-lg": ["var(--font-be-vietnam-pro)", "var(--font-pretendard)", "system-ui", "sans-serif"],
        "headline-lg": ["var(--font-be-vietnam-pro)", "var(--font-pretendard)", "system-ui", "sans-serif"],
        "headline-md": ["var(--font-be-vietnam-pro)", "var(--font-pretendard)", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["var(--font-be-vietnam-pro)", "var(--font-pretendard)", "system-ui", "sans-serif"],
        "body-lg": ["var(--font-plus-jakarta-sans)", "var(--font-pretendard)", "system-ui", "sans-serif"],
        "body-md": ["var(--font-plus-jakarta-sans)", "var(--font-pretendard)", "system-ui", "sans-serif"],
        "body-sm": ["var(--font-plus-jakarta-sans)", "var(--font-pretendard)", "system-ui", "sans-serif"],
        "label-md": ["var(--font-plus-jakarta-sans)", "var(--font-pretendard)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600", letterSpacing: "-0.01em" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
        "headline-lg-mobile": ["22px", { lineHeight: "30px", fontWeight: "600" }],
      },
      spacing: {
        base: "8px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        gutter: "16px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "40px",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        card: "20px",
      },
    },
  },
  plugins: [],
};

export default config;
